version: '3.8'

services:
  postgres:
    container_name: postscore_db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postscore

  app:
    container_name: postscore_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    environment:
      DB_URL: ${DB_URL}
    volumes:
      - ./app:/app
    networks:
      - postscore

  pgweb:
    container_name: pgweb  # optional
    restart: always  # optional
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - postgres:postgres  # my database container is called postgres, not db
    environment:
      - PGWEB_DATABASE_URL=${DB_URL}
    depends_on:
      - postgres  # my database container is called postgres, not db
    networks:
      - postscore

volumes:
  pgdata:

networks:
  postscore:
    driver: bridge